peso:
  junior:
    ebitdaMMA: 10
    ebitdaAREA: 10
    mloa: 10
  pleno:
    ebitdaMMA: 15
    ebitdaAREA: 17.5
    mloa: 17.5
  senior:
    ebitdaMMA: 20
    ebitdaAREA: 30
    mloa: 20
  socio:
    ebitdaMMA: 20
    ebitdaAREA: 30
    mloa: 20